#!/usr/bin/env bash

# This will run makemigrations and migrate for the django appliciation after
# deleting the current migrations. You may or may not need to delete your
# currently database as well, by default this is ./db.sqlite3


# Check that the virtual environment is enabled
if ! env | grep VIRTUAL_ENV &>/dev/null; then
    echo "You should probably activate your venv"
    exit 1
fi

# Find all the migration folders for each application and remove the migrations
for dir in $(find . -name migrations); do
    for file in $(ls $dir | awk '/[0-9]{4}.*\.py$/'); do
        filename="${dir}/${file}"
        echo "Deleting $filename"
        if ! rm "$filename"; then
            echo "> Failed."
            exit 1
        fi
    done
done


# Find the manage.py script
if [[ -x "./manage.py" ]]; then
    m="manage.py"
elif [[ -x "./manage" ]]; then
    m="manage"
else
    echo "where is the manage script!!"
    exit 1
fi

if ! ./${m} makemigrations; then
    echo "> failed to makemigrations"
    exit 1
fi

if ! ./${m} migrate; then
    echo "> failed to migrate"
    exit 1
fi
